Dockerfile, README.md
Just allows this project to be built and used in Docker fairly easily
This pull request makes the following changes:
* Adds `Dockerfile`
* Adds instructions to `README.md` on how to use it
=> Dockerfile fun times

src/main/java/org/sonatype/repository/conan/internal/AssetKind.groovy, src/main/java/org/sonatype/repository/conan/internal/ConanFormat.java, src/main/java/org/sonatype/repository/conan/internal/ConanRecipeSupport.groovy, src/main/java/org/sonatype/repository/conan/internal/metadata/ConanAbsoluteUrlRemover.java, src/main/java/org/sonatype/repository/conan/internal/metadata/ConanHashVerifier.java, src/main/java/org/sonatype/repository/conan/internal/metadata/ConanManifest.java, src/main/java/org/sonatype/repository/conan/internal/metadata/ConanMetadata.java, src/main/java/org/sonatype/repository/conan/internal/proxy/ConanProxyFacet.java, src/main/java/org/sonatype/repository/conan/internal/proxy/ConanProxyHelper.groovy, src/main/java/org/sonatype/repository/conan/internal/proxy/ConanProxyRecipe.groovy, src/main/java/org/sonatype/repository/conan/internal/security/ConanFormatSecurityContributor.java, src/main/java/org/sonatype/repository/conan/internal/security/ConanSecurityFacet.java, src/main/java/org/sonatype/repository/conan/internal/ui/ConanBrowseNodeGenerator.java, src/main/java/org/sonatype/repository/conan/internal/ui/UiPluginDescriptorImpl.java, src/main/java/org/sonatype/repository/conan/internal/utils/ConanFacetUtils.java
=> CONAN-8 Added @'since documentation to all classes to reference version 0.0.1

src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipe.groovy, src/main/java/org/sonatype/repository/conan/internal/hosted/HostedHandlers.java, src/test/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipeTest.java
Fixes #21 
This also sets the order to GAV format
=> Added conan export to allowed upload

docs/CONAN_USER_DOCUMENTATION.md
Addresses https://github.com/sonatype-nexus-community/nexus-repository-conan/issues/27
=> ISSUE-27 Add documentation for setup

src/main/java/org/sonatype/repository/conan/internal/AssetKind.groovy, src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipe.groovy, src/main/java/org/sonatype/repository/conan/internal/hosted/HostedHandlers.java
Issue: https://github.com/sonatype-nexus-community/nexus-repository-conan/issues/25
Adds support for conan_sources.tgz
=> ISSUE 25: And sources TGZ support

src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipe.groovy, src/main/java/org/sonatype/repository/conan/internal/hosted/HostedHandlers.java
A basic ping response satisfies the /v1/ping request
* Fixes #31
=> Simple 200 response for a ping

src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedFacet.java, src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipe.groovy, src/main/java/org/sonatype/repository/conan/internal/hosted/HostedHandlers.java
The download url paths need to be remapped to GAV order
* Fixes #30
=> remap download_url to GAV

Dockerfile, README.md, pom.xml
Updates the NXRM version to 3.14.0-04
=> Update version to 3.14.0-04

src/main/java/org/sonatype/repository/conan/internal/proxy/ConanProxyFacet.java, src/main/java/org/sonatype/repository/conan/internal/proxy/ConanProxyRecipe.groovy, src/main/java/org/sonatype/repository/conan/internal/proxy/matcher/ConanMatcher.groovy
Looks like the introduction of the ping endpoint for new clients broke the proxy
* Fixes #33
=> ping endpoint added to proxy

README.md
Since we can now install using a kar file, life is much easier for everyone. Add install instructions for this, sit back, and enjoy :)
This pull request makes the following changes:
README updates
cc @DarthHater @bhamail @mcculls
=> Kar bundle install instructions

src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedFacet.java, src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipe.groovy, src/main/java/org/sonatype/repository/conan/internal/hosted/HostedHandlers.java, src/main/java/org/sonatype/repository/conan/internal/hosted/UploadUrlManager.java
Implemented handler for 
/v1/conans/{${PROJECT}}/{${VERSION}}/{${GROUP}}/{${STATE}}//packages/{${DIGEST}}
endpoint, which fixes downloading packages by Conan client 1.14+
It relates to the following issue #s:
* Fixes #60
=> Get package snapshot

nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipe.groovy, nexus-repository-conan/src/test/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipeTest.java, nexus-repository-conan/src/test/java/org/sonatype/repository/conan/internal/proxy/matcher/ConanProxyRecipeTest.java
Fixed competitiveness in ha_clusted disabling and in hosted repo disabling
=> NEXUS-21938 Fixed ha_clusted and hosted flags competitive work

nexus-repository-conan-it/src/test/java/org/sonatype/nexus/plugins/conan/internal/CleanupTaskConanProxyIT.java, nexus-repository-conan-it/src/test/resources/conan/dowload_urls_lib, nexus-repository-conan/pom.xml, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/cleanup/ConanCleanupPolicyConfiguration.java, nexus-repository-conan/src/main/resources/static/rapture/NX/conan/view/repository/recipe/ConanProxy.js
NEXUS-21939 Implemented Cleanup policy for Conan Proxy plug-in
=> NEXUS-21939 Implemented Cleanup policy for Conan Proxy plug-in

nexus-repository-conan-it/src/test/java/org/sonatype/nexus/plugins/conan/internal/ConanRoutingRuleIT.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/common/v1/ConanControllerV1.java, nexus-repository-conan/src/main/resources/static/rapture/NX/conan/view/repository/recipe/ConanProxy.js
NEXUS-21942 Implemented Routing Rules support in Conan plug-in
=> NEXUS-21942 Implemented Routing Rules support in Conan plug-in

nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/proxy/v1/ConanProxyApiV1.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/proxy/v1/ConanProxyRecipe.groovy
NEXUS-22102 Fixed problem with conan proxy auth
=> NEXUS-22102 Fixed problem with conan proxy auth

nexus-repository-conan-it/src/test/java/org/sonatype/nexus/plugins/conan/rest/ConanResourceIT.java, nexus-repository-conan-it/src/test/java/org/sonatype/nexus/plugins/conan/rest/ConanResourceITSupport.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/api/ConanProxyRepositoryApiRequest.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/rest/ConanProxyRepositoriesApiResource.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/rest/ConanProxyRepositoriesApiResourceDoc.java
NEXUS-22137: Added REST API for Conan repositories
=> NEXUS-22137: Added REST API for Conan repositories

nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/ConanRecipeSupport.groovy, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipe.groovy, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/proxy/v1/ConanProxyRecipe.groovy
https://issues.sonatype.org/browse/NEXUS-22631
=> NEXUS-22631: Conan plugin logs warnings on boot

README.md
=> NEXUS-22487: Added help page

nexus-repository-conan/src/main/java/org/sonatype/repository/conan/upgrade/ConanModel.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/upgrade/ConanUpgrade_1_1.java, nexus-repository-conan/src/test/java/org/sonatype/repository/conan/upgrade/ConanUpgrade_1_1_Test.groovy, pom.xml
https://issues.sonatype.org/browse/NEXUS-22747
=> NEXUS-22747 Conan: Database migration for 1.0.0 release

CONTRIBUTORS.md, nexus-repository-conan-it/src/test/java/org/sonatype/nexus/plugins/conan/internal/ConanProxyIT.java, nexus-repository-conan-it/src/test/resources/conan/digest, nexus-repository-conan-it/src/test/resources/conan/download_urls_lib, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/AssetKind.groovy, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/common/v1/ConanControllerV1.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/common/v1/ConanRoutes.groovy, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/proxy/ConanProxyHelper.groovy, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/proxy/v1/ConanProxyControllerV1.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/proxy/v1/ConanProxyFacet.java
Added update option handling for conan install command
=> Nexus-22733:  Added update option handling for conan install command

nexus-repository-conan-it/pom.xml, nexus-repository-conan/pom.xml, pom.xml
NEXUS-21945: Updated Conan plug-in to release version
=> NEXUS-21945: Updated Conan plug-in to release version

nexus-repository-conan-it/src/test/java/org/sonatype/nexus/plugins/conan/internal/ConanProxyIT.java, nexus-repository-conan-it/src/test/java/org/sonatype/nexus/plugins/conan/internal/ConanProxySearchIT.java, nexus-repository-conan-it/src/test/resources/conan/digest_non_package_search, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/ConanSystemProperties.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/common/v1/ConanRoutes.groovy, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipe.groovy, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/proxy/ConanProxyHelper.groovy, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/proxy/v1/ConanProxyControllerV1.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/proxy/v1/ConanProxyFacet.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/proxy/v1/ConanProxyHandlers.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/ui/ConanBrowseNodeFilter.java, nexus-repository-conan/src/test/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipeTest.java, nexus-repository-conan/src/test/java/org/sonatype/repository/conan/internal/ui/ConanBrowseNodeFilterTest.java
https://issues.sonatype.org/browse/NEXUS-22735
=> NEXUS-22735: Conan search command improvement

nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/common/v1/ConanControllerV1.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/common/v1/ConanRoutes.groovy, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedMetadataFacetSupport.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/v1/ConanHostedControllerV1.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/v1/HostedHandlers.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/proxy/v1/ConanProxyControllerV1.java, nexus-repository-conan/src/test/java/org/sonatype/repository/conan/internal/hosted/ConanHostedMetadataFacetSupportTest.java, nexus-repository-conan/src/test/java/org/sonatype/repository/conan/internal/hosted/ConanHostedRecipeTest.java
Was fixed the following issues
https://issues.sonatype.org/browse/NEXUS-22878
https://issues.sonatype.org/browse/NEXUS-22877
=> NEXUS-22878 : Conan hosted routing issue and NEXUS-22877 Conan upload command does not work

.gitignore, .travis.yml, Dockerfile, README.md
Nexus-20700: Merged master in Conan feature branch
=> Nexus-20700: conan proxy official support merge master

nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedMetadataFacetSupport.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/v1/ConanHostedControllerV1.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/v1/ConanHostedFacet.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/v1/HostedHandlers.java
NEXUS-23607: Fixed Conan hosted upload
=> NEXUS-23607: Fixed Conan hosted upload

nexus-repository-conan/src/main/java/org/sonatype/repository/conan/upgrade/ConanUpgrade_1_1.java, nexus-repository-conan/src/test/java/org/sonatype/repository/conan/upgrade/ConanUpgrade_1_1_Test.groovy
NEXUS-23112: Fixed migration for hosted repo
=> NEXUS-23112: Fixed migration for hosted repo

nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/AssetKind.groovy, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/ConanHostedMetadataFacetSupport.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/v1/ConanHostedFacet.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/hosted/v1/HostedHandlers.java, nexus-repository-conan/src/test/java/org/sonatype/repository/conan/internal/hosted/ConanHostedMetadataFacetSupportTest.java
Fixed download and upload urls file generation
=> NEXUS-23353: Fixed download and upload urls file generation

pom.xml
Update NXRM parent version for release
=> NEXUS-23506: Updating parent and nxrm version.

nexus-repository-conan-it/pom.xml, nexus-repository-conan/pom.xml, pom.xml
Increase the project version. To pass release automation
=> bump project version

nexus-repository-conan-it/pom.xml, nexus-repository-conan-it/src/test/java/org/sonatype/nexus/plugins/conan/ConanITConfig.java, nexus-repository-conan-it/src/test/java/org/sonatype/nexus/plugins/conan/internal/CleanupTaskConanProxyIT.java, nexus-repository-conan-it/src/test/java/org/sonatype/nexus/plugins/conan/internal/ConanProxyIT.java, nexus-repository-conan-it/src/test/java/org/sonatype/nexus/plugins/conan/internal/ConanProxySearchIT.java, nexus-repository-conan-it/src/test/java/org/sonatype/nexus/plugins/conan/rest/ConanResourceIT.java, pom.xml
Ticket: https://issues.sonatype.org/browse/NEXUS-24319
#124 should be closed once current one is merged to master
=> NEXUS-24319: Aligned Conan ITs with renewed IT infrastructure

nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/orient/hosted/ConanHostedMetadataFacetSupport.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/orient/hosted/v1/ConanHostedFacet.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/internal/orient/hosted/v1/HostedHandlers.java
Fixed response in case of not found package
=> Fixed response in case of not found package

nexus-repository-conan/src/main/java/org/sonatype/repository/conan/rest/ConanProxyRepositoriesApiResource.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/rest/ConanProxyRepositoriesApiResourceBeta.java, nexus-repository-conan/src/main/java/org/sonatype/repository/conan/rest/ConanProxyRepositoriesApiResourceV1.java
ticket: https://issues.sonatype.org/browse/NEXUS-24905
tested manually. REST API was not broken and works properly.
=> fix broken api

pom.xml
fix: https://github.com/sonatype-nexus-community/nexus-repository-conan/pull/125#discussion_r438422713
=> remove unnecessary comment
